---
# Default for Node IP
node_ip: "{{ ansible_default_ipv4.address }}"

# Default for Node Name
node_name: "{{ ansible_hostname }}"

# Default Value for user zookeeper
kafka_user: "{{ username_system }}"

# Default Value for group zookeeper
kafka_group: "{{ group_system }}"

# Default Value for home dir kafka on host
user_home_directory: '/opt/kafka'

# Default for Block Wipe
block_device: 'sdb'

# Default for Block Wipe
block_wipe: 'false'

# Default for Enable ZFS
enable_zfs: 'false'

# Default for ZFS Pool Name
zfs_pool_name: 'data'

# Default for ZFS Pool Wipe
zfs_pool_wipe: 'false'

# Default for ZFS Dataset Wipe
zfs_dataset_wipe: 'false'

# Default for Enable LVM
enable_lvm: 'false'

# Default for LVM Volume Group Name
lvm_vg_name: 'vg-data'

# Default for Sanoid Version
java_package_name: 'openjdk-11-jre-headless'