---
- hosts: kafka
  any_errors_fatal: true
  roles:
  - role: facts

- hosts: kafka
  any_errors_fatal: true
  roles:
  - role: common

# - hosts: kafka
#   any_errors_fatal: true
#   serial: 1
#   roles:
#   - role: kafka
