---
- include: facts.yml

- include: rm_cfg_svc.yml

- include: rm_cfg_umount.yml

- include: rm_cfg_clean_kafka.yml

- include: rm_cfg_lvm.yml

- include: rm_cfg_block.yml

- include: rm_cfg_user.yml

- include: rm_cfg_java.yml