---
- name: Restart Node Operating System
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  async: 1
  poll: 0    

- name: Wait For Node to Be Ready Operating System
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600