---
- name: Uninstall Java 
  apt:
    name: "{{ java_package_name }}"
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
