---
- name: Check ZFS Pool Lists
  command: zpool list
  register: zfs_pool_lists

- name: Clean ZFS Pool if 'zfs_pool_wipe' is true
  command: zpool destroy -f {{ zfs_pool_name }}
  when:
    - zfs_pool_lists.stdout.find(zfs_pool_name) != -1
    - zfs_pool_wipe