---
# Default for Node IP
node_ip: "{{ ansible_default_ipv4.address }}"

# Default for Node Name
node_name: "{{ ansible_hostname }}"

# Default for Enable IPVS
enable_ip_vs: 'false'

# Default for IPVS Mode
ip_vs_mode: 'lc'

# Default for Block Wipe
block_wipe: 'false'

# Default for Enable ZFS
enable_zfs: 'false'

# Default for ZFS Pool Name
zfs_pool_name: 'data'

# Default for ZFS Pool Wipe
zfs_pool_wipe: 'false'

# Default for ZFS Dataset Wipe
zfs_dataset_wipe: 'false'

# Default for Enable LVM
enable_lvm: 'false'

# Default for LVM Volume Group Name
lvm_vg_name: 'vg-data'

# Default Value for user zookeeper
zookeeper_user: "{{ username_system }}"

# Default Value for group zookeeper
zookeeper_group: "{{ group_system }}"

# Default Value for home dir kafka on host
user_home_directory: '/opt/kafka'