---
- name: Backup config file server.properties 
  command: mv /opt/kafka/config/server.properties /opt/kafka/config/server.properties.orig~

- name: Create New config file server.properties
  template:
    src: server.properties.j2
    dest: "{{ user_home_directory }}/config/server.properties"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"

- name: Backup config file log4j.properties 
  command: mv /opt/kafka/config/log4j.properties /opt/kafka/config/log4j.properties.orig~

- name: Create New config file log4j.properties
  template:
    src: log4j.properties.j2
    dest: "{{ user_home_directory }}/config/log4j.properties"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"

- name: Backup config file producer.properties
  command: mv /opt/kafka/config/producer.properties /opt/kafka/config/producer.properties.orig~

- name: Create New config file server.properties
  template:
    src: producer.properties.j2
    dest: "{{ user_home_directory }}/config/producer.properties"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"

- name: Backup config file consumer.properties
  command: mv /opt/kafka/config/consumer.properties /opt/kafka/config/consumer.properties.orig~

- name: Create New config file server.properties
  template:
    src: consumer.properties.j2
    dest: "{{ user_home_directory }}/config/consumer.properties"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"

- name: Create New config file jaas_kafka_client.conf
  template:
    src: jaas_kafka_client.conf.j2
    dest: "{{ user_home_directory }}/config/jaas_kafka_client.conf"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"

- name: Create New config file jaas_kafka_server.conf
  template:
    src: jaas_kafka_server.conf.j2
    dest: "{{ user_home_directory }}/config/jaas_kafka_server.conf"
    mode: 0644
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"
