---
- name: Download Kafka Source Package
  get_url:
    url: http://www-eu.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /tmp/kafka.tgz
    mode: 0755

- name: Unarchive Kafka Source
  unarchive:
    src: /tmp/kafka.tgz
    dest: "{{ user_home_directory }}"
    remote_src: yes
    extra_opts: 
    - --strip-components=1

- name: Remove Kafka Source
  file:
    path: /tmp/kafka.tgz
    state: absent
