---
- name: Create Kafka Data Directory
  file:
    path: "{{ user_home_directory }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set Kafka Data Storage Mountpoint to Kafka Data Directory (ZFS)
  shell: zfs set mountpoint="{{ user_home_directory }}"/data {{ zfs_pool_name }}/kafka
  when:
    - enable_zfs == 'true'
  register: zfs_mount_status

- name: Restart Node Operating System
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  async: 1
  poll: 0    
  when:
    - zfs_mount_status.changed
    - enable_zfs == 'true'

- name: Wait For Node to Be Ready Operating System
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600
  when:
    - zfs_mount_status.changed
    - enable_zfs == 'true'


- name: Set Kafka Data Storage Mountpoint to Kafka Data Directory (LVM)
  mount:
    src: "/dev/{{ lvm_vg_name }}/lv-kafka"
    path: "{{ user_home_directory }}/data"
    fstype: xfs
    opts: discard,noatime
    state: mounted
    backup: yes
  when:
    - enable_lvm == 'true'