---
# - name: Create Directory Home for Kafka User
#   file:
#     path: "{{ user_home_directory }}"
#     state: directory

- name: Creating System Group Kafka
  group:
    name: "{{ group_system }}"
    state: present
    system: yes


- name: Creating User Kafka
  user:
    name: "{{ username_system }}"
    groups: "{{ group_system }}"
    state: present
    home: "{{ user_home_directory }}"
    system: yes