---
- name: Unmount Kafka Data Storage Directory
  mount:
    path: "{{ user_home_directory }}/data"
    state: unmounted
   
- name: Format Filesystem Kafka Data Storage (LVM)
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg--data-lv--kafka
    force: yes

- name: Set Kafka Data Storage Mountpoint to Kafka Data Directory (LVM)
  mount:
    src: "/dev/{{ lvm_vg_name }}/lv-kafka"
    path: "{{ user_home_directory }}/data"
    fstype: xfs
    opts: discard,noatime
    state: mounted
    backup: yes